version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://fabdbuser:NUUU3Gy8XIEOdI%t6LJ^@192.168.99.159:5432/fabdb
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  frontend:
    build: ./frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
      - "/app/dist"
    ports:
      - 8080:8080
